# Generated by Django 5.2.5 on 2025-08-13 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active.', verbose_name='active')),
                ('name', models.CharField(help_text='Display name of the agent', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description of the agent's purpose and capabilities")),
                ('agent_type', models.CharField(choices=[('researcher', 'Researcher'), ('analyst', 'Analyst'), ('coder', 'Coder'), ('writer', 'Writer'), ('manager', 'Manager'), ('custom', 'Custom')], default='custom', help_text='Type of the agent', max_length=20)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('thinking', 'Thinking'), ('executing', 'Executing'), ('error', 'Error'), ('updating', 'Updating')], default='offline', help_text='Current status of the agent', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration settings for the agent')),
                ('last_active', models.DateTimeField(blank=True, help_text='When the agent was last active', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active.', verbose_name='active')),
                ('name', models.CharField(help_text='Unique name for this capability', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the capability')),
                ('required_parameters', models.JSONField(blank=True, default=dict, help_text='Required parameters for this capability in JSON format')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Agent Capability',
                'verbose_name_plural': 'Agent Capabilities',
            },
        ),
        migrations.CreateModel(
            name='AgentCapabilityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this capability is currently enabled for the agent')),
                ('config', models.JSONField(blank=True, default=dict, help_text="Configuration specific to this agent's capability")),
                ('agent', models.ForeignKey(help_text='The agent that has this capability', on_delete=django.db.models.deletion.CASCADE, related_name='capability_mappings', to='agents.agent')),
                ('capability', models.ForeignKey(help_text='The capability being assigned to the agent', on_delete=django.db.models.deletion.CASCADE, related_name='agent_mappings', to='agents.agentcapability')),
            ],
            options={
                'verbose_name': 'Agent Capability Mapping',
                'verbose_name_plural': 'Agent Capability Mappings',
                'ordering': ['agent__name', 'capability__name'],
                'unique_together': {('agent', 'capability')},
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='The actual content of the message')),
                ('is_from_agent', models.BooleanField(default=False, help_text='Whether the message is from the agent (True) or to the agent (False)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the message in JSON format')),
                ('agent', models.ForeignKey(help_text='The agent this message is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Agent Message',
                'verbose_name_plural': 'Agent Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='agents_agen_agent_i_01e21b_idx'), models.Index(fields=['is_from_agent', 'created_at'], name='agents_agen_is_from_15099e_idx')],
            },
        ),
    ]
